language: c

sudo: required

services:
- docker

env:
  matrix:
  - IMAGE=ubuntu:18.04
  - IMAGE=ubuntu:16.04

script:
- docker run -it --env-file <(env | grep ^GITHUB) --name sub.sh -v "$PWD/sub.sh:/sub.sh" "$IMAGE" bash -c '[[ -f ~/.profile ]] && source ~/.profile; /sub.sh'
- docker start -ia sub.sh

after_success:
- pushd web
- make
- echo sub.sh > build/CNAME
- touch build/.nojekyll
- popd

deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: web/build
  on:
    branch: master
    env: IMAGE=ubuntu:18.04
