name: sub.sh

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Too many arguments
      run: ./sub.sh one two; [[ $? -eq 2 ]]

    - name: Unknown option
      run: ./sub.sh --unknown-option; [[ $? -eq 2 ]]

    - name: Non-directory exists
      run: ./sub.sh "$(mktemp)"; [[ $? -eq 2 ]]

    - name: Non-directory exists (symbolic link)
      run: |
        target="$(mktemp)"
        link="$(mktemp)"
        ln -sf "$target" "$link"
        ./sub.sh "$(mktemp)"; [[ $? -eq 2 ]]

  verify:
    name: Verify
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ['ubuntu:18.04', 'centos:7.4.1708']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run
      run: docker run -i --name sub.sh -v "$PWD/sub.sh:/sub.sh" ${{ matrix.image }} bash -c '[[ -f ~/.profile ]] && source ~/.profile; /sub.sh'

    - name: Rerun
      run: docker start -a sub.sh

  publish:
    name: Publish
    needs: verify
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build web
      run: |
        pushd web
        make
        echo sub.sh > build/CNAME
        touch build/.nojekyll
        popd

    - name: GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: web/build
